# Site settings
title: Shravan Kuchkula
description: A blog for my projects
baseurl: "/cards-jekyll-template" # the subpath of your site, e.g. /blog
url: "https://shravan-kuchkula.github.io" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Shravan Kuchkula
user_description: Data Scientist in training
email: shravan.kuchkula@gmail.com
twitter_username: shra1
github_username:  shravan-kuchkula
disqus_username: lorem_ipsum

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/


# html minify
compress_html:
  clippings: all
  comments: all
  endings: []
  profile: false

# Links to include in menu navigation
# For external links add external: true
links:
  - title: Home
    url: /
  - title: Series
    url: /series
  - title: Tags
    url: /tags
  - title: About Me
    url: /about

# exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules']
